baseURL = 'https://zawhmqo.github.io'
languageCode = 'en-us'
title = 'Digital Solace'
theme = 'archie'
copyright = "W'zamqo Rhid"

# Syntax highlighting
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

pagination.pagerSize = 25

[outputs]
home = ['html', 'rss']

[params]
mode = "auto"
useCDN = true
subtitle = "Sorcery with source code"
mathjax = false
katex = false

[params.meta]
favicon = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[params.social]]
name = "Bluesky"
icon = "cloud"
url = "https://bsky.app/profile/wzamqo.bsky.social"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/zawhmqo"

[caches]
[caches.images]
dir = ':cacheDir/images'
